{{- if .Values.supavisor.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supabase.supavisor.fullname" . }}
  labels:
    {{- include "supabase.supavisor.labels" . | nindent 4 }}
spec:
  {{- if not .Values.supavisor.autoscaling.enabled }}
  replicas: {{ .Values.supavisor.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "supabase.supavisor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.supavisor.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "supabase.supavisor.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.supavisor.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "supabase.supavisor.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.supavisor.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "supabase.supavisor.name" $ }}
          securityContext:
            {{- toYaml .Values.supavisor.securityContext | nindent 12 }}
          image: "{{ .Values.supavisor.image.repository }}:{{ .Values.supavisor.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.supavisor.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.supavisor.environment }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- if .Values.db.enabled }}
            - name: POSTGRES_HOSTNAME
              value: {{ include "supabase.db.fullname" . }}
            - name: DATABASE_URL
              value: "ecto://supabase_admin:$(POSTGRES_PASSWORD)@$(POSTGRES_HOSTNAME):$(POSTGRES_PORT)/_supabase"
            {{- end }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.secret.db.secretRef }}
                  name: {{ .Values.secret.db.secretRef }}
                  key: {{ .Values.secret.db.secretRefKey.password | default "password" }}
                  {{- else }}
                  name: {{ include "supabase.secret.db" . }}
                  key: password
                  {{- end }}
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  {{- if .Values.secret.jwt.secretRef }}
                  name: {{ .Values.secret.jwt.secretRef }}
                  key: {{ .Values.secret.jwt.secretRefKey.secret | default "secret" }}
                  {{- else }}
                  name: {{ include "supabase.secret.jwt" . }}
                  key: secret
                  {{- end }}
            - name: VAULT_ENC_KEY
              valueFrom:
                secretKeyRef:
                  {{- if .Values.secret.jwt.secretRef }}
                  name: {{ .Values.secret.jwt.secretRef }}
                  key: {{ .Values.secret.jwt.secretRefKey.secret | default "secret" }}
                  {{- else }}
                  name: {{ include "supabase.secret.jwt" . }}
                  key: secret
                  {{- end }}
            - name: API_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  {{- if .Values.secret.jwt.secretRef }}
                  name: {{ .Values.secret.jwt.secretRef }}
                  key: {{ .Values.secret.jwt.secretRefKey.secret | default "secret" }}
                  {{- else }}
                  name: {{ include "supabase.secret.jwt" . }}
                  key: secret
                  {{- end }}
            - name: METRICS_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  {{- if .Values.secret.jwt.secretRef }}
                  name: {{ .Values.secret.jwt.secretRef }}
                  key: {{ .Values.secret.jwt.secretRefKey.secret | default "secret" }}
                  {{- else }}
                  name: {{ include "supabase.secret.jwt" . }}
                  key: secret
                  {{- end }}
          {{- with .Values.supavisor.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.supavisor.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
          {{- with .Values.supavisor.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command:
            - /bin/sh
            - -c
            - '/app/bin/migrate && /app/bin/supavisor eval "$(cat /etc/pooler/pooler.exs)" && /app/bin/server'
          volumeMounts:
            - name: pooler-config
              mountPath: /etc/pooler
              readOnly: true
          {{- with .Values.supavisor.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: pooler-config
          configMap:
            name: {{ include "supabase.supavisor.fullname" . }}-config
      {{- with .Values.supavisor.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.supavisor.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.supavisor.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.supavisor.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}