{{- if .Values.supavisor.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "supabase.supavisor.fullname" . }}
  labels:
    {{- include "supabase.supavisor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.supavisor.service.type }}
  ports:
    - port: {{ .Values.supavisor.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "supabase.supavisor.selectorLabels" . | nindent 4 }}
{{- end }}